import Link from "next/link";

export default function TermsPage() {
  return (
    <>
      <section className="bg-gradient-to-br from-slate-900 to-blue-900 py-16 text-white">
        <div className="mx-auto max-w-4xl px-6">
          <h1 className="text-3xl font-bold tracking-tight md:text-4xl">
            Terms of Service
          </h1>
          <p className="mt-4 text-slate-200">
            Rules governing the use of PolicyCopilot.
          </p>
        </div>
      </section>

      <section className="bg-slate-50 py-16">
        <div className="prose prose-slate mx-auto max-w-3xl px-6 leading-relaxed">
          <p className="text-sm font-medium text-slate-500">
            Effective Date: June 2026
          </p>
          <p className="mt-4 text-slate-700">
            These Terms of Service govern the use of the PolicyCopilot website
            and services.
          </p>
          <p className="mt-3 text-slate-700">
            By using the platform, you agree to these terms.
          </p>

          <div className="mt-10 space-y-8">
            <div>
              <h2 className="text-xl font-semibold text-slate-900">
                Use of the Service
              </h2>
              <p className="mt-3 text-slate-700">
                PolicyCopilot provides AI-assisted tools to help interpret
                credit policies and evaluate loan eligibility scenarios.
              </p>
              <p className="mt-3 text-slate-700">
                The service is intended for informational and analytical
                purposes and should not be considered financial advice.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-slate-900">
                Acceptable Use
              </h2>
              <p className="mt-3 text-slate-700">
                Users agree not to:
              </p>
              <ul className="mt-3 list-disc space-y-2 pl-6 text-slate-700">
                <li>misuse the platform for unlawful purposes</li>
                <li>attempt to disrupt system functionality</li>
                <li>upload harmful or malicious content</li>
                <li>attempt unauthorized access to the platform</li>
              </ul>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-slate-900">
                Accuracy of Information
              </h2>
              <p className="mt-3 text-slate-700">
                While PolicyCopilot aims to provide accurate policy insights,
                results generated by the AI system may require verification
                against official policy documents.
              </p>
              <p className="mt-3 text-slate-700">
                Users should confirm final lending decisions using internal
                policy guidelines.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-slate-900">
                Intellectual Property
              </h2>
              <p className="mt-3 text-slate-700">
                All software, content, and branding related to PolicyCopilot
                remain the intellectual property of the platform owners.
              </p>
              <p className="mt-3 text-slate-700">
                Users may not reproduce or redistribute the service without
                permission.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-slate-900">
                Limitation of Liability
              </h2>
              <p className="mt-3 text-slate-700">
                PolicyCopilot is provided &quot;as is&quot; without warranties of any
                kind. We are not liable for decisions made based on system
                outputs.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-slate-900">
                Changes to Terms
              </h2>
              <p className="mt-3 text-slate-700">
                We may update these Terms periodically. Continued use of the
                platform after changes constitutes acceptance of the updated
                terms.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-slate-900">
                Contact
              </h2>
              <p className="mt-3 text-slate-700">
                For questions regarding these terms, contact:
              </p>
              <p className="mt-2">
                <Link
                  href="mailto:support@policycopilot.ai"
                  className="font-medium text-blue-600 hover:underline"
                >
                  support@policycopilot.ai
                </Link>
              </p>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
